apiVersion: v1
kind: Pod
metadata:
  name: director
  namespace: towerdefence
spec:
  containers:
    - name: director
      image: emortalmc/mm-director:dev
      imagePullPolicy: Never

  serviceAccountName: matchmaker
  automountServiceAccountToken: true