FROM golang:alpine as go
WORKDIR /app
ENV GO111MODULE=on

COPY go.mod .
RUN go mod download

COPY . .
RUN go build -o matchfunction pkg/matchfunction/main.go

FROM alpine

COPY --from=go /app/matchfunction /app/matchfunction
CMD ["/app/matchfunction"]