FROM golang:alpine as go
WORKDIR /app
ENV GO111MODULE=on

COPY go.mod .
RUN go mod download

COPY . .
RUN go build -o director pkg/director/main.go

FROM alpine

COPY --from=go /app/director /app/director
CMD ["/app/director"]